/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#2592ff",
        "secondary-container": "#ffbf00",
        "surface-container-high": "#392520",
        "error": "#ffb4ab",
        "secondary": "#ffe2ab",
        "inverse-on-surface": "#402c26",
        "on-primary-container": "#541100",
        "on-secondary-fixed": "#261a00",
        "tertiary": "#a5c8ff",
        "primary-fixed-dim": "#ffb5a0",
        "on-surface": "#fddbd3",
        "on-primary-fixed": "#3b0900",
        "on-surface-variant": "#e7bdb2",
        "surface-dim": "#1f0f0b",
        "surface-container": "#2d1b16",
        "background": "#0A0A0A",
        "inverse-surface": "#fddbd3",
        "on-secondary": "#402d00",
        "on-error-container": "#ffdad6",
        "outline": "#ad887e",
        "error-container": "#93000a",
        "surface-tint": "#ffb5a0",
        "on-secondary-container": "#6d5000",
        "on-error": "#690005",
        "on-primary": "#601400",
        "secondary-fixed-dim": "#fbbc00",
        "tertiary-fixed": "#d4e3ff",
        "on-tertiary-container": "#002a53",
        "surface": "#1f0f0b",
        "on-background": "#fddbd3",
        "surface-container-lowest": "#190a06",
        "primary": "#FF4500",
        "outline-variant": "#5d4038",
        "on-tertiary": "#00315e",
        "surface-variant": "#44302a",
        "primary-fixed": "#ffdbd1",
        "surface-bright": "#49342f",
        "inverse-primary": "#b12d00",
        "surface-container-low": "#291712",
        "on-tertiary-fixed": "#001c3a",
        "primary-container": "#ff5625",
        "tertiary-fixed-dim": "#a5c8ff",
        "on-primary-fixed-variant": "#872000",
        "secondary-fixed": "#ffdfa0",
        "on-secondary-fixed-variant": "#5c4300",
        "on-tertiary-fixed-variant": "#004785",
        "surface-container-highest": "#44302a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "label-caps": ["Space Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h1": ["Space Grotesk", "sans-serif"],
        "code": ["Inter", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "code": ["14px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "400" }],
        "h3": ["24px", { "lineHeight": "1.3", "letterSpacing": "0em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
